# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:

    - &OrdererOrg

        Name: OrdererOrg

        # ID to load the MSP definition as
        ID: OrdererMSP

        # MSPDir is the filesystem path which contains the MSP configuration
        MSPDir: crypto-config/ordererOrganizations/orderer.u-hopper.com/msp

        # Policies defines the set of policies at this level of the config tree
        # For organization policies, their canonical path is usually
        #   /Channel/<Application|Orderer>/<OrgName>/<PolicyName>
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('OrdererMSP.peer')"


    - &UHopperOrg
        Name: UHopperOrgMSP

        ID: UHopperOrgMSP

        MSPDir: crypto-config/peerOrganizations/org.u-hopper.com/msp

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.org.u-hopper.com
              Port: 7051

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('UHopperOrgMSP.admin', 'UHopperOrgMSP.peer', 'UHopperOrgMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('UHopperOrgMSP.admin', 'UHopperOrgMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('UHopperOrgMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('UHopperOrgMSP.peer')"


    - &UHopperOrg1
        Name: UHopperOrg1MSP

        ID: UHopperOrg1MSP

        MSPDir: crypto-config/peerOrganizations/org1.u-hopper.com/msp

        AnchorPeers:
            - Host: peer0.org1.u-hopper.com
              Port: 7051

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('UHopperOrg1MSP.admin', 'UHopperOrg1MSP.peer', 'UHopperOrg1MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('UHopperOrg1MSP.admin', 'UHopperOrg1MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('UHopperOrg1MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('UHopperOrg1MSP.peer')"

Capabilities:
    # Channel capabilities apply to both the orderers and the peers and must be
    # supported by both.
    # Set the value of the capability to true to require it.
    Channel: &ChannelCapabilities
        V2_0: true

    # Orderer capabilities apply only to the orderers, and may be safely
    # used with prior release peers.
    # Set the value of the capability to true to require it.
    Orderer: &OrdererCapabilities
        V2_0: true

    # Application capabilities apply only to the peer network, and may be safely
    # used with prior release orderers.
    # Set the value of the capability to true to require it.
    Application: &ApplicationCapabilities
        V2_0: true

################################################################################
#
#   SECTION: Application
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for application related parameters
#
################################################################################
Application: &ApplicationDefaults

    # Organizations is the list of orgs which are defined as participants on
    # the application side of the network
    Organizations:

    # Policies defines the set of policies at this level of the config tree
    # For Application policies, their canonical path is
    #   /Channel/Application/<PolicyName>

    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        # BlockValidation specifies what signatures must be included in the block
        # from the orderer for the peer to validate it.
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        LifecycleEndorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
        Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"

    Capabilities:
        <<: *ApplicationCapabilities

################################################################################
#
#   SECTION: Orderer
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for orderer related parameters
#
################################################################################
Orderer: &OrdererDefaults

    # Orderer Type: The orderer implementation to start
    # Available types are "solo" and "kafka"
    OrdererType: solo

    Addresses:
        - orderer.orderer.u-hopper.com:7050

    # Batch Timeout: The amount of time to wait before creating a batch
    BatchTimeout: 1s

    # Batch Size: Controls the number of messages batched into a block
    BatchSize:

        # Max Message Count: The maximum number of messages to permit in a batch
        MaxMessageCount: 10

        # Absolute Max Bytes: The absolute maximum number of bytes allowed for
        # the serialized messages in a batch.
        AbsoluteMaxBytes: 99 MB

        # Preferred Max Bytes: The preferred maximum number of bytes allowed for
        # the serialized messages in a batch. A message larger than the preferred
        # max bytes will result in a batch larger than preferred max bytes.
        PreferredMaxBytes: 512 KB

    Kafka:
        # Brokers: A list of Kafka brokers to which the orderer connects
        # NOTE: Use IP:port notation
        Brokers:
            - 127.0.0.1:9092

    # Organizations is the list of orgs which are defined as participants on
    # the orderer side of the network
    Organizations:


    # Policies defines the set of policies at this level of the config tree
    # For Orderer policies, their canonical path is
    #   /Channel/Orderer/<PolicyName>
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        # BlockValidation specifies what signatures must be included in the block
        # from the orderer for the peer to validate it.
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"




################################################################################
#
#   CHANNEL
#
#   This section defines the values to encode into a config transaction or
#   genesis block for channel related parameters.
#
################################################################################
Channel: &ChannelDefaults
    # Policies defines the set of policies at this level of the config tree
    # For Channel policies, their canonical path is
    #   /Channel/<PolicyName>
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        # BlockValidation specifies what signatures must be included in the block
        # from the orderer for the peer to validate it.
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

    # Capabilities describes the channel level capabilities, see the
    # dedicated Capabilities section elsewhere in this file for a full
    # description
    Capabilities:
      <<: *ChannelCapabilities
################################################################################
#
#   Profile
#
#   - Different configuration profiles may be encoded here to be specified
#   as parameters to the configtxgen tool
#
################################################################################
Profiles:

    OrdererGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            UHopperOrgUHopperOrg1Consortium:
                Organizations:
                    - *UHopperOrg
                    - *UHopperOrg1
    consentmanagementchannel:
        <<: *ChannelDefaults
        Consortium: UHopperOrgUHopperOrg1Consortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *UHopperOrg
                - *UHopperOrg1
            Capabilities:
                <<: *ApplicationCapabilities

    TwoOrdereEtcdRaft:
        <<: *ChannelDefaults
        Capabilities:
            <<: *ChannelCapabilities
        Orderer:
            <<: *OrdererDefaults
            OrdererType: etcdraft
            EtcdRaft:
                Consenters:
                - Host: orderer.orderer.u-hopper.com
                  Port: 7050
                  ClientTLSCert: crypto-config/ordererOrganizations/orderer.u-hopper.com/orderers/orderer.orderer.u-hopper.com/tls/server.crt
                  ServerTLSCert: crypto-config/ordererOrganizations/orderer.u-hopper.com/orderers/orderer.orderer.u-hopper.com/tls/server.crt
                - Host: orderer2.orderer.u-hopper.com
                  Port: 7050
                  ClientTLSCert: crypto-config/ordererOrganizations/orderer.u-hopper.com/orderers/orderer2.orderer.u-hopper.com/tls/server.crt
                  ServerTLSCert: crypto-config/ordererOrganizations/orderer.u-hopper.com/orderers/orderer2.orderer.u-hopper.com/tls/server.crt

            Addresses:
                - orderer.orderer.u-hopper.com:7050
                - orderer2.orderer.u-hopper.com:7050

            Organizations:
            - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities

        Application:
            <<: *ApplicationDefaults
            Organizations:
            - <<: *OrdererOrg
        Consortiums:
            UHopperOrg1Consortium:
                Organizations:
                    - *UHopperOrg
                    - *UHopperOrg1
