OrdererOrgs:

  - Name: OrdererOrg
    Domain: orderer.u-hopper.com
    EnableNodeOUs: true

    Specs:
      - Hostname: orderer
      - Hostname: orderer2

PeerOrgs:

  - Name: UHopperOrg
    Domain: org.u-hopper.com
    EnableNodeOUs: true

    Template:
      Count: 2

    Users:
      Count: 1


  - Name: UHopperOrg1
    Domain: org1.u-hopper.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
