version: '2'

networks:
  basic:
    external:
      name: tsundoku-blockchain-${ENV}

services:
  orderer.orderer.u-hopper.com:
    container_name: orderer.orderer.u-hopper.com-${ENV}
    image: hyperledger/fabric-orderer:2.3.2
    environment:
      - FABRIC_LOGGING_SPEC=info
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp

      - ORDERER_GENERAL_TLS_ENABLED=false
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]

      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    # ports:
    #   - 7050:7050
    volumes:
        - ./../config/:/etc/hyperledger/configtx
        - ./../crypto-config/ordererOrganizations/orderer.u-hopper.com/orderers/orderer.orderer.u-hopper.com/:/etc/hyperledger/msp/orderer
        - ./../crypto-config/peerOrganizations/org.u-hopper.com/peers/peer0.org.u-hopper.com/:/etc/hyperledger/msp/peerUHopperOrg
        - ./../crypto-config/peerOrganizations/org1.u-hopper.com/peers/peer0.org1.u-hopper.com/:/etc/hyperledger/msp/peerUHopperOrg1
        - ./../crypto-config/ordererOrganizations/orderer.u-hopper.com/orderers/orderer.orderer.u-hopper.com/tls/:/var/hyperledger/orderer/tls
        - ./../data/orderer:/var/hyperledger/production
    networks:
      basic:
          aliases:
              - orderer.orderer.u-hopper.com

  peer0.org.u-hopper.com:
    container_name: peer0.org.u-hopper.com-${ENV}
    image: hyperledger/fabric-peer:2.3.2
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.org.u-hopper.com
      - FABRIC_LOGGING_SPEC=info
      - CORE_CHAINCODE_LOGGING_LEVEL=debug
      - CORE_PEER_LOCALMSPID=UHopperOrgMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer0.org.u-hopper.com:7051
      # # the following setting starts chaincode containers on the same
      # # bridge network as the peers
      # # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=tsundoku-blockchain-${ENV}
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer0.org.u-hopper.com:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.

      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org.u-hopper.com:7051

      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    env_file:
      - couch_db_peer0.org0.env
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    # command: peer node start --peer-chaincodedev=true
    # ports:
    #   - 7051:7051
    #   - 7053:7053
    volumes:
        - /var/run:/host/var/run/
        - ./../crypto-config/peerOrganizations/org.u-hopper.com/peers/peer0.org.u-hopper.com/msp:/etc/hyperledger/msp/peer
        - ./../crypto-config/peerOrganizations/org.u-hopper.com/users:/etc/hyperledger/msp/users
        - ./../config:/etc/hyperledger/configtx
        - ./../crypto-config/peerOrganizations/org.u-hopper.com/peers/peer0.org.u-hopper.com/tls:/etc/hyperledger/fabric/tls
        - ./../crypto-config/ordererOrganizations/orderer.u-hopper.com/orderers/orderer.orderer.u-hopper.com/msp/tlscacerts/:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/orderer.u-hopper.com/orderers/orderer.orderer.u-hopper.com/msp/tlscacerts/
        - ./../data/peer0.org.u-hopper.com:/var/hyperledger/production
    depends_on:
      - orderer.orderer.u-hopper.com
      - couchdb.peer0.org.u-hopper.com
    networks:
      basic:
          aliases:
              - peer0.org.u-hopper.com

  couchdb.peer0.org.u-hopper.com:
    container_name: couchdb.peer0.org.u-hopper.com-${ENV}
    image: hyperledger/fabric-couchdb:0.4.16
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    env_file:
      - couch_db_peer0.org0.env
    # ports:
    #   - 5984:5984
    networks:
      basic:
          aliases:
            - couchdb.peer0.org.u-hopper.com
    volumes:
      - ./../data/couchdb.peer0.org.u-hopper.com:/opt/couchdb/data


  peer0.org1.u-hopper.com:
    container_name: peer0.org1.u-hopper.com-${ENV}
    image: hyperledger/fabric-peer:2.3.2
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.org1.u-hopper.com
      - FABRIC_LOGGING_SPEC=info
      - CORE_CHAINCODE_LOGGING_LEVEL=debug
      - CORE_PEER_LOCALMSPID=UHopperOrg1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer0.org1.u-hopper.com:7051
      # # the following setting starts chaincode containers on the same
      # # bridge network as the peers
      # # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=tsundoku-blockchain-${ENV}
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer0.org1.u-hopper.com:5984

      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.u-hopper.com:7051

      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    env_file:
      - couch_db_peer0.org1.env
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    # command: peer node start --peer-chaincodedev=true
    # ports:
    #   - 7151:7051
    #   - 7153:7053
    volumes:
        - /var/run:/host/var/run/
        - ./../crypto-config/peerOrganizations/org1.u-hopper.com/peers/peer0.org1.u-hopper.com/msp:/etc/hyperledger/msp/peer
        - ./../crypto-config/peerOrganizations/org1.u-hopper.com/users:/etc/hyperledger/msp/users
        - ./../config:/etc/hyperledger/configtx
        - ./../crypto-config/peerOrganizations/org1.u-hopper.com/peers/peer0.org1.u-hopper.com/tls:/etc/hyperledger/fabric/tls
        - ./../crypto-config/ordererOrganizations/orderer.u-hopper.com/orderers/orderer.orderer.u-hopper.com/msp/tlscacerts/:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/orderer.u-hopper.com/orderers/orderer.orderer.u-hopper.com/msp/tlscacerts/
        - ./../data/peer0.org1.u-hopper.com:/var/hyperledger/production
    depends_on:
      - orderer.orderer.u-hopper.com
      - couchdb.peer0.org1.u-hopper.com
    networks:
      basic:
          aliases:
              - peer0.org1.u-hopper.com


  couchdb.peer0.org1.u-hopper.com:
    container_name: couchdb.peer0.org1.u-hopper.com-${ENV}
    image: hyperledger/fabric-couchdb:0.4.16
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    env_file:
      - couch_db_peer0.org1.env
    # ports:
    #    - 5985:5984
    networks:
      basic:
          aliases:
            - couchdb.peer0.org1.u-hopper.com
    volumes:
      - ./../data/couchdb.peer0.org1.u-hopper.com:/opt/couchdb/data



  cliUHopperOrg:
    container_name: cliUHopperOrg-${ENV}
    image: hyperledger/fabric-tools:2.3.2
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=info
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org.u-hopper.com:7051
      - CORE_PEER_LOCALMSPID=UHopperOrgMSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org.u-hopper.com/users/Admin@org.u-hopper.com/msp
      - CORE_CHAINCODE_KEEPALIVE=10

      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org.u-hopper.com/peers/peer0.org.u-hopper.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org.u-hopper.com/peers/peer0.org.u-hopper.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org.u-hopper.com/peers/peer0.org.u-hopper.com/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run:/host/var/run/
        - ./../chaincode-go/tsundoku_chaincode:/opt/gopath/src/tsundoku_chaincode/
        - ./../crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./../crypto-config/peerOrganizations/org.u-hopper.com/users:/etc/hyperledger/msp/users
        - ./../config:/etc/hyperledger/configtx
        - ./chiancode_pkg/:/opt/gopath/src/github.com/hyperledger/fabric/peer/chaincode_pkg
    networks:
        basic:
          aliases:
              - cliUHopperOrg

  cliUHopperOrg1:
    container_name: cliUHopperOrg1-${ENV}
    image: hyperledger/fabric-tools:2.3.2
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=info
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.u-hopper.com:7051
      - CORE_PEER_LOCALMSPID=UHopperOrg1MSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.u-hopper.com/users/Admin@org1.u-hopper.com/msp
      - CORE_CHAINCODE_KEEPALIVE=10

      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.u-hopper.com/peers/peer0.org1.u-hopper.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.u-hopper.com/peers/peer0.org1.u-hopper.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.u-hopper.com/peers/peer0.org1.u-hopper.com/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run:/host/var/run/docker.sock
        - ./../chaincode-go/tsundoku_chaincode:/opt/gopath/src/tsundoku_chaincode/
        - ./../crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./../config:/etc/hyperledger/configtx
        - ./chiancode_pkg/:/opt/gopath/src/github.com/hyperledger/fabric/peer/chaincode_pkg
    networks:
        basic:
          aliases:
              - cliUHopperOrg1

